const localData = [
    { id: 0, name: "Kathleen Pusker", table: 0 },
    { id: 1, name: "Steve Pusker", table: 0 },
    { id: 2, name: "Robert Kenney Jr", table: 0 },
    { id: 3, name: "Jessica Kenney", table: 0 },
    { id: 4, name: "Robert Kenney Sr.", table: 0 },
    { id: 5, name: "Stephanie Pusker", table: 0 },
    { id: 6, name: "Katherine Brown", table: 0 },
    { id: 7, name: "Diana LaMondia", table: 0 },
    { id: 8, name: "Natalie Robichaud", table: 0 },
    { id: 9, name: "Cody Cobb", table: 0 },
    { id: 10, name: "Patrick Hufnagel", table: 0 },
    { id: 11, name: "Angie Hager", table: 0 },
    { id: 12, name: "Emily Hager", table: 0 },
    { id: 13, name: "Caroline Brantley", table: 0 },
    { id: 14, name: "James Brantley", table: 0 },
    { id: 15, name: "Candace Raines", table: 0 },
    { id: 16, name: "Jason Raines", table: 0 },
    { id: 17, name: "Jessica Corey", table: 0 },
    { id: 18, name: "David Alaimo", table: 0 },
    { id: 19, name: "Terry Im", table: 0 },
    { id: 20, name: "Michele Im", table: 0 },
    { id: 21, name: "Taylor Griffin", table: 0 },
    { id: 22, name: "Nikki Paxton", table: 0 },
    { id: 23, name: "Anthony Sinphay", table: 0 },
    { id: 24, name: "Kaitlyn Bouchillon", table: 0 },
    { id: 25, name: "Aaron Bouchillon", table: 0 },
    { id: 26, name: "Alexis Hilliar-Hine", table: 0 },
    { id: 27, name: "Calen Hilliar", table: 0 },
    { id: 28, name: "Kristin Riley", table: 0 },
    { id: 29, name: "Brad Riley", table: 0 },
    { id: 30, name: "Frances Wolfe-Bertling", table: 0 },
    { id: 31, name: "Aaron Wolfe-Bertling", table: 0 },
    { id: 32, name: "Adam Wolfe-Bertling", table: 0 },
    { id: 33, name: "Bridget Patel", table: 0 },
    { id: 34, name: "Shil Patel", table: 0 },
    { id: 35, name: "Margaret Myers", table: 0 },
    { id: 36, name: "Ben Myers", table: 0 },
    { id: 37, name: "Reggie Titmas", table: 0 },
    { id: 38, name: "Elizabeth Borowski", table: 0 },
    { id: 39, name: "Tori Henderson", table: 0 },
    { id: 40, name: "Kim Balogh", table: 0 },
    { id: 41, name: "Andy Balogh", table: 0 },
    { id: 42, name: "Martial Robichaud", table: 0 },
    { id: 43, name: "Amy Robichaud", table: 0 },
    { id: 44, name: "Tim Wolfe", table: 0 },
    { id: 45, name: "Pete Brulla", table: 0 },
    { id: 46, name: "James Wolfe", table: 0 },
    { id: 47, name: "Linda Wolfe", table: 0 },
    { id: 48, name: "Chris Blassingame", table: 0 },
    { id: 49, name: "Natalia Brown", table: 0 },
    { id: 50, name: "David Goodwin", table: 0 },
    { id: 51, name: "David Chea", table: 0 },
    { id: 52, name: "Tori Chea", table: 0 },
    { id: 53, name: "Judy Ruhling", table: 0 },
    { id: 54, name: "Jay Ruhling", table: 0 },
    { id: 55, name: "Stephen Ruhling", table: 0 },
    { id: 56, name: "Allie Pincus", table: 0 },
    { id: 57, name: "Richard Knox", table: 0 },
    { id: 58, name: "Suzanne Knox", table: 0 },
    { id: 59, name: "Katie Eleam", table: 0 },
    { id: 60, name: "Amy Russ", table: 0 },
    { id: 61, name: "Cindy Liu", table: 0 },
    { id: 62, name: "Andy Zhang", table: 0 },
    { id: 63, name: "Kelsi Kahler", table: 0 },
    { id: 64, name: "Johanna Davis", table: 0 },
    { id: 65, name: "Eric Davis", table: 0 },
    { id: 66, name: "Elizabeth Carbone", table: 0 },
    { id: 67, name: "John David Narramore", table: 0 },
    { id: 68, name: "Staci Kehir", table: 0 },
    { id: 69, name: "Russ Kehir", table: 0 },
    { id: 70, name: "Diana Gomez", table: 0 },
    { id: 71, name: "Brianna Byerly", table: 0 },
    { id: 72, name: "Jeannine Streetman", table: 0 },
    { id: 73, name: "Stan Streetman", table: 0 },
];

export default localData;
